### PR TITLE
Update com.obsproject.Studio.BlackMagicLibs.json

### PR DESCRIPTION
**Pull request by sat3ll**
Update to Desktop Video 11.1

### CODE REVIEW

**Comment by Erick555** [comment]
@sat3ll you need to bump [shared-modules](https://github.com/flathub/shared-modules) submodule to get [udev fix](https://github.com/flathub/shared-modules/commit/9f3bee567bf58a55ec92632f5030d88277e7728d).

**Comment by sat3ll** [comment]
> @sat3ll you need to bump [shared-modules](https://github.com/flathub/shared-modules) submodule to get [udev fix](https://github.com/flathub/shared-modules/commit/9f3bee567bf58a55ec92632f5030d88277e7728d).

That should go to a different PR. This PR only deals with the BlackMagic extension.

**Comment by Erick555** [comment]
@sat3ll no, you won't be able to build anything unless you make update I mentioned.

**Comment by sat3ll** [comment]
> @sat3ll no, you won't be able to build anything unless you make update I mentioned.

It doesn't build with the buildbot because this extension requires you to manually fetch the tar.gz file. It will build locally as instructed by https://github.com/flathub/com.obsproject.Studio/wiki/BlackMagic-Support

**Comment by Erick555** [comment]
> It doesn't build with the buildbot because this extension requires you to manually fetch the tar.gz file. It will build locally as instructed by https://github.com/flathub/com.obsproject.Studio/wiki/BlackMagic-Support.

@sat3ll I'm afraid you didn't read the actual [buildbot logs](https://flathub.org/builds/#/builders/12/builds/244). It failed before it even touched your extension. It will fail if you even didn't change anything. It won't build neither locally or remotely unless you update submodules. This is my point which I have hard time to sell here :smile:.

**Comment by Erick555** [comment]
I created [PR](https://github.com/flathub/com.obsproject.Studio/pull/27) which will solve the issue.

**Comment by sat3ll** [comment]
Strange, I got it to build this morning:
```
$ flatpak-builder builddir --force-clean com.obsproject.Studio.BlackMagicLibs.json --user --install
Downloading sources
Initializing build dir
Committing stage init to cache
Starting build of com.obsproject.Studio.BlackMagicLibs
========================================================================
Building module blackmagic in /tmp/com.obsproject.Studio/.flatpak-builder/build/blackmagic-1
========================================================================
Running: tar -xf other/x86_64/desktopvideo-11.1a11-x86_64.tar.gz
Running: install -Dm644 --target-directory=$FLATPAK_DEST desktopvideo-11.1a11-x86_64/usr/lib/{*.so,blackmagic/DesktopVideo/libc++*.so.1}
Committing stage build-blackmagic to cache
Cleaning up
Committing stage cleanup to cache
Finishing app
Please review the exported files and the metadata
Committing stage finish to cache
Exporting com.obsproject.Studio.BlackMagicLibs to repo
Commit: 87def687acb739ecf40143718c1e244656a56040c604cd0c1dc2bb029ee4a072
Metadata Total: 5
Metadata Written: 2
Content Total: 7
Content Written: 0
Content Bytes Written: 0 (0 bytes)
Installing runtime/com.obsproject.Studio.BlackMagicLibs/x86_64/stable
Pruning cache
$
```
But I suppose there's no harm in updating the shared-modules.

**Comment by Erick555** [comment]
I guess you didn't run `flatpak update` before building it. Relevant changes landed just yesterday.

**Comment by TingPing** [comment]
This also needs the runtime to be bumped to 5.13 now.

**Pull request merged**
